import Head from 'next/head'
import Link from "next/link"


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex h-screen'>
        <div className='m-auto bg-transparent text-5xl hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-8 px-16  border-blue-500 border-8 rounded-full shadow-xl hover:border-transparent'>
            <Link href="./signin"> Log in </Link>
        </div>
          
      </main>
    </>
  )
}
